Feature: add nextjs
serudda/discord-bot pull request #10
Opened 2024-10-14 07:33 UTC by Zyruks

## Changes Made 🎉

- [x] **feat**: Added basic card component to display cards with rarity-based filtering
- [x] **style**: Implemented animations and hover effects for cards in `card-animations.css`
- [x] **chore**: Updated configuration for ESLint, scripts, and project structure
- [x] **chore**: 🔧 update API server with CORS middleware
- [x] **chore**: 🔧 update lint-staged config with app-specific ESLint settings
- [x] **chore**: 🗂️ add basic folder structure for project organization
- [x] **feat**: 🏎️ add turbo.json configuration for Next.js app
- [x] **chore**: 🔧 add basic config for Tailwind, PostCSS, TypeScript, and ESLint
- [x] **feat**: ✨ integrate tRPC API handlers and webhooks for Next.js app
- [x] **chore**: 🔧 update TypeScript configuration for Next.js project
- [x] **chore**: 🔧 update Next.js configuration for improved DX and CI
- [x] **chore**: 🔧 update tooling and add TypeScript configuration for ESLint
- [x] **chore**: 🔧 update `eslint.config.js` for apps/bot and next

### Describe Changes

This PR introduces multiple updates across the project:

- Added a basic card component to display cards with rarity-based filtering and associated hover/animation effects.
- Updated various configurations including ESLint, scripts, and TypeScript settings for both the bot and Next.js apps.
- Integrated `turbo.json` for enhanced build management with Turborepo.
- Applied linting fixes across 38 files to comply with the latest ESLint rules.
- Added folder structure to improve project organization (e.g., `src/common`, `src/pages`, `src/components`).
- Added tRPC API handlers and webhooks for the Next.js app and configured environment variable validation using `env.mjs`.
- Implemented CORS middleware for the API server and updated `lint-staged` settings for app-specific ESLint configurations.

## Visuals (Optional)

https://github.com/user-attachments/assets/5eef9032-06a2-40de-ad3e-622db2a9655c

## Checklist ✅

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes (if applicable).
- [x] All new and existing tests passed.

2024-10-14 07:35 UTC, Zyruks commented on apps/bot/src/utils/getFilesRecursively.ts
> +  let results: string[] = [];
Esto lo cambia el eslint en automatico.

Recuerdo leer porque era mejor [] a Array pero ha esta hora ya no genero Seru.!

2024-10-14 23:40 UTC, serudda requested changes

2024-10-14 23:40 UTC, serudda commented on apps/bot/src/commands/tcg/add-coins.ts
> +import { ErrorMessages } from '@discord-bot/error-handler';
```suggestion
import { ErrorMessages, type ErrorCode  } from '@discord-bot/error-handler';
```

2024-10-14 23:40 UTC, serudda commented on apps/bot/src/commands/hello.ts
> +import { SlashCommandBuilder } from 'discord.js';
```suggestion
import { SlashCommandBuilder, type CommandInteraction } from 'discord.js';
```

2024-10-14 23:40 UTC, serudda commented on apps/bot/src/commands/ping.ts
> +import { SlashCommandBuilder } from 'discord.js';
```suggestion
import { SlashCommandBuilder, type CommandInteraction } from 'discord.js';
```

2024-10-14 23:40 UTC, serudda commented on apps/bot/src/commands/tcg/add-coins.ts
> +import { SlashCommandBuilder } from 'discord.js';
```suggestion
import { SlashCommandBuilder,  type CommandInteraction } from 'discord.js';
```

2024-10-14 23:40 UTC, serudda commented on apps/bot/src/commands/tcg/add-coins.ts
> +      if (response?.result?.coins) {
Esto no valida, esto simplemente hace que el typescript no rompa... pero la validacion no la hace

2024-10-14 23:40 UTC, serudda commented on apps/bot/src/utils/getFilesRecursively.ts
> +  let results: string[] = [];
Va

2024-10-14 23:40 UTC, serudda commented on packages/api/src/schema/account.schema.ts
> +import type { TypeOf } from 'zod';
Esta es la correcta, por que separarlo?

2024-10-14 23:40 UTC, serudda commented on packages/api/src/schema/card.schema.ts
> +import type { TypeOf } from 'zod';
Esta es la correcta, por que separarlo?

2024-10-14 23:40 UTC, serudda commented on packages/api/src/schema/lemonSqueezy.schema.ts
> +import type { TypeOf } from 'zod';
No separar

2024-10-14 23:40 UTC, serudda commented on packages/api/src/schema/subscription.schema.ts
> +import type { TypeOf } from 'zod';
No separar

2024-10-14 23:40 UTC, serudda commented on packages/api/src/schema/subscriptionPlan.schema.ts
> +import type { TypeOf } from 'zod';
No separar

2024-10-14 23:40 UTC, serudda commented on packages/api/src/schema/user.schema.ts
> +import type { TypeOf } from 'zod';
No separar

2024-10-15 01:37 UTC, Zyruks commented on apps/bot/src/commands/tcg/buy-pack.ts
> +import { ErrorMessages } from '@discord-bot/error-handler';
Done!

2024-10-15 01:38 UTC, Zyruks commented on apps/bot/src/commands/tcg/buy-pack.ts
> +import { AttachmentBuilder, SlashCommandBuilder } from 'discord.js';
Done!

2024-10-15 01:38 UTC, Zyruks commented on apps/bot/src/commands/tcg/collection.ts
> +import { ErrorMessages } from '@discord-bot/error-handler';
Done!

2024-10-15 01:38 UTC, Zyruks commented on apps/bot/src/commands/tcg/collection.ts
> +import { SlashCommandBuilder } from 'discord.js';
Done!

2024-10-15 01:39 UTC, Zyruks commented on apps/bot/src/commands/tcg/collection.ts
> +      if (response?.result?.collection) {
Done!

2024-10-15 01:39 UTC, Zyruks commented on apps/bot/src/commands/tcg/create-card.ts
> +import { SlashCommandBuilder } from 'discord.js';
Done!

2024-10-15 01:39 UTC, Zyruks commented on apps/bot/src/commands/tcg/create-card.ts
> +import { ErrorMessages } from '@discord-bot/error-handler';
Done!

2024-10-15 01:40 UTC, Zyruks commented on apps/bot/src/commands/tcg/create-card.ts
> +      if (response?.result?.card) {
Done!

2024-10-15 16:22 UTC, Zyruks commented on packages/api/src/controllers/card.controller.ts
> +      const userCards = randomCards.map(async (card) => {
Ese randomCards no es una promesa ahora dentro si porque se espera la transaccion
```ts 
  await prismaTransaction.userCard.create({
          data: {
            userId: user.id,
            cardId: card.id,
          },
        });
        ```
        
        Pero ese await estaba de mas

2024-10-15 16:24 UTC, Zyruks commented on packages/api/src/schema/subscription.schema.ts
> +import type { TypeOf } from 'zod';
Done!

2024-10-15 16:24 UTC, Zyruks commented on packages/api/src/schema/lemonSqueezy.schema.ts
> +import type { TypeOf } from 'zod';
Done!

2024-10-15 16:24 UTC, Zyruks commented on packages/api/src/schema/card.schema.ts
> +import type { TypeOf } from 'zod';
Done!

2024-10-15 16:25 UTC, Zyruks commented on packages/api/src/schema/account.schema.ts
> +import type { TypeOf } from 'zod';
Done!

2024-10-15 16:25 UTC, Zyruks commented on packages/api/src/index.ts
> +import { appRouter } from './root';
Done!

2024-10-15 16:25 UTC, Zyruks commented on packages/api/src/controllers/subscription.controller.ts
> +import type { Params } from '../common';
Done!

2024-10-15 16:25 UTC, Zyruks commented on packages/api/src/controllers/lemonSqueezy.controller.ts
> +import { Response, TRPCErrorCode } from '../common';
Done!

2024-10-15 16:25 UTC, Zyruks commented on packages/api/src/controllers/card.controller.ts
> +      if (!randomCardsResponse?.result?.cards) {
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/web/package.json
> +    "dev:deprecated": "astro dev",
Astro lo vamos a sacar, entonces para no agregarlo en este PR que ya es grande simplemente agregue deprecated para que no corra a la hora de hacer pnpm dev

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/utils/loadEvents.ts
> +        if (event?.name && event.execute) {
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/utils/loadCommands.ts
> +import { Collection } from 'discord.js';
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/utils/getFilesRecursively.ts
> +    if (stat?.isDirectory()) {
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/events/ready.ts
> +import { ActivityType } from 'discord.js';
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/commands/tcg/wallet.ts
> +import { SlashCommandBuilder } from 'discord.js';
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/commands/tcg/wallet.ts
> +import { ErrorMessages } from '@discord-bot/error-handler';
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/commands/tcg/start-game.ts
> +      if (response?.result?.coins) {
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/commands/tcg/start-game.ts
> +import { SlashCommandBuilder } from 'discord.js';
Done!

2024-10-15 16:26 UTC, Zyruks commented on apps/bot/src/commands/tcg/start-game.ts
> +import { ErrorMessages, UserError } from '@discord-bot/error-handler';
Done!

2024-10-15 16:27 UTC, Zyruks commented on apps/bot/src/commands/tcg/set-coins.ts
> +import { SlashCommandBuilder } from 'discord.js';
Done!

2024-10-15 16:27 UTC, Zyruks commented on apps/bot/src/commands/tcg/set-coins.ts
> +import { ErrorMessages } from '@discord-bot/error-handler';
Done!

2024-10-15 16:27 UTC, Zyruks commented on apps/bot/src/commands/ping.ts
> +import { SlashCommandBuilder } from 'discord.js';
Done!

2024-10-15 16:37 UTC, Zyruks commented on apps/bot/src/commands/tcg/add-coins.ts
> +      if (response?.result?.coins) {
Done!

2024-10-15 16:41 UTC, serudda requested changes

2024-10-15 16:41 UTC, serudda commented on packages/api/src/controllers/card.controller.ts
>  } from '../schema/card.schema';
```suggestion
import type {
  AddCoinsInputType,
  BuyPackInputType,
  CreateCardInputType,
  GetAllCardsByRarityInputType,
  GetCollectionInputType,
  GetRandomCardByRarityInputType,
  GetRandomCardsInputType,
  SetCoinsInputType,
} from '../schema/card.schema';
```

2024-10-15 16:41 UTC, serudda commented on packages/api/src/controllers/card.controller.ts
> +      const userCards = randomCards.map(async (card) => {
Pero si tengo awaits internos, quiere decir que estoy esperando una promesa... por ende deberia esperar tambien afuera

2024-10-15 16:41 UTC, serudda commented on packages/api/src/controllers/lemonSqueezy.controller.ts
> +    headers.append('Authorization', `Bearer ${process.env.LEMON_SQUEEZY_API_KEY!}`);
Entre el primero y el segundo, me parece mas limpio el as string, al menos se que tipo espero

2024-10-15 16:41 UTC, serudda commented on packages/api/src/controllers/subscription.controller.ts
>  } from '../schema/subscription.schema';
Por que? si como estaba es perfecto... si todos los imports internos son "type", poner el type afuera

2024-10-15 16:41 UTC, serudda commented on packages/api/src/controllers/user.controller.ts
> +  type RegisterUserInputType,
WHYYYY

2024-10-15 16:41 UTC, serudda commented on packages/api/src/controllers/user.controller.ts
> +        userId: newUser.result.user.id,
Es mas seguro el primero

2024-10-15 16:46 UTC, Zyruks commented on apps/bot/src/commands/tcg/buy-pack.ts
> +          images.push(card?.image!);
Done!

2024-10-15 16:47 UTC, Zyruks commented on packages/api/src/controllers/card.controller.ts
>  } from '../schema/card.schema';
Done!

2024-10-15 16:49 UTC, Zyruks commented on packages/api/src/controllers/user.controller.ts
> +        userId: newUser.result.user.id,
Este no necesita los ? ni as string porque se valida arriba que tenga id

```ts
   if (!newUser?.result?.user?.id) {
      return {
        result: {
          status: Response.ERROR,
          message: UserError.UserNotFound,
        },
      };
    }

    // Create account
    const newAccount = await createAccountHandler({
      ctx,
      input: {
        type: 'discord',
        provider: 'discord',
        providerAccountId: discordId,
        userId: newUser.result.user.id,
      },
    });
```

Esto fue lo que hablamos que luego lo volveremos typeguards

2024-10-15 16:49 UTC, Zyruks commented on packages/api/src/controllers/user.controller.ts
> +  type RegisterUserInputType,
![WhyPersianRoomCatGuardianGIF](https://github.com/user-attachments/assets/8c63520d-50b7-4953-9bb7-f9522d3ed1f3)

2024-10-15 16:50 UTC, Zyruks commented on packages/api/src/controllers/lemonSqueezy.controller.ts
> +    headers.append('Authorization', `Bearer ${process.env.LEMON_SQUEEZY_API_KEY!}`);
Done!

2024-10-15 16:53 UTC, Zyruks commented on packages/api/src/controllers/card.controller.ts
> +      const userCards = randomCards.map(async (card) => {
Es que un mapeo no es asyncrono, internamente si hace cosa async por eso dentro del map tiene una funcion que si es asincrona.

```ts
 const userCards = randomCards.map(async (card) => {
        if (!card) return;

        // Add user card
        await prismaTransaction.userCard.create({
          data: {
            userId: user.id,
            cardId: card.id,
          },
        });
      });
```

Incluso sin linter typescript dice que esta de mas


![image](https://github.com/user-attachments/assets/d2daa2a3-da53-4efa-9587-821a275d704b)

2024-10-15 17:13 UTC, serudda approved these changes

2024-10-15 17:13 UTC, merged