Feature: user profile and collection page
serudda/discord-bot pull request #16
Opened 2024-10-17 05:28 UTC by Zyruks

## Changes Made 🎉

- [x] feat: added UserProfilePage with user profile and card collection display
- [x] feat: added RaritySection and UserCardRarities components to organize cards by rarity
- [x] feat: added UserProfileImage component with card count and hover effects
- [x] feat: integrated createCardCountMap utility for managing card counts
- [x] style: included new emblem images (COMMON, EPIC, FOIL, LEGENDARY, RARE, UNCOMMON) under public assets
- [x] style: updated global styles and animations to support new components
- [x] build: modified package.json for both bot and nextjs apps to include required dependencies
- [x] build: updated Tailwind configuration to support new UI components and design updates

### Describe Changes

This PR introduces the UserProfilePage, where users can view their profile image and card collection organized by rarity. The following key components and features have been added:
- **UserProfilePage**: Displays user details, such as profile image and total card count.
- **UserProfileImage**: Renders the user's profile image with a 3D flip effect showing the total cards owned.
- **RaritySection**: Displays cards grouped by rarity (LEGENDARY, EPIC, RARE, UNCOMMON, COMMON).
- **UserCardRarities**: Provides a grid of card rarities with an option to toggle showing unknown cards.
- **createCardCountMap**: A utility to map card IDs to the quantity of cards owned by the user.

Additional emblem images have been added to represent different card rarities, and global styles have been updated to support the new UI components.

## Visuals (Optional)

https://github.com/user-attachments/assets/8f5a380a-90a7-4225-9713-7b9c3032f257

## Checklist ✅

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have tested the changes thoroughly to ensure no regression issues.

2024-10-17 16:55 UTC, serudda requested changes

2024-10-17 16:55 UTC, serudda commented on apps/bot/package.json
> +    "dev2": "pnpm with-env node --import tsx src/index.ts",
🤢🤮 what?

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/components.json
> +  "$schema": "https://ui.shadcn.com/schema.json",
que son components.json? eso pa que?

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/package.json
> +    "lucide-react": "^0.453.0",
esto pa que?

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/components/UserCollection/components/RaritySection.tsx
> +  ownedCardIds: Set<string>;
Por q Set y no Array?

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/components/UserCollection/components/RaritySection.tsx
> +  groupByRarity: (rarity: string) => Card[];
```suggestion
  groupByRarity: (rarity: string) => Array<Card>;
```

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/components/UserCollection/components/UserCardRarities.tsx
> +/* _components/UserCardRarities.tsx */
what?

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/components/UserCollection/components/UserCardRarities.tsx
> +export const UserCardRarities = ({ showUnknown, setShowUnknown }: UserCardRaritiesProps) => {
Yo cambiaria de nombre por que estas mezclando las rarezas, el checkbox, y mas cosas que pueden ir dentro... entonces ya deja de ser UserCardRarities, si tiene mas cosas dnetro

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/components/UserCollection/components/UserProfileImage.tsx
> +      '[ profile-image ]',
what??

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/components/UserCollection/components/UserProfileImage.tsx
> +      '[ profile-back ]',
what??

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/components/UserCollection/utils/cardUtils.ts
> + * Creates a map of card IDs to the quantity of cards owned
Que es "Crear un mapa.." no explica en realidad que quieres hacer con este metodo?

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/components/UserCollection/utils/cardUtils.ts
> + * Creates a map of card IDs to the quantity of cards owned
lo miro de mis formas, y no entiendo una monda pa que es este funcion

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/lib/utils.ts
> +import { clsx, type ClassValue } from "clsx"
yo separaria utils en diferentes archivos: /utils/cn.ts

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/pages/[...slug]/index.tsx
> +import { createCardCountMap, RaritySection, UserCardRarities, UserProfileImage } from '../../components/UserCollection';
Si tenemos ~/utils, por que no ~/components

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/pages/[...slug]/index.tsx
> +  const [showUnknown, setShowUnknown] = useState(false);
podriamos usar otro name que no sea "unknown"? es palabra reservada... y ademas me confunde y no me da contexto

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/pages/[...slug]/index.tsx
> +  const ownedCardIds = new Set(collectionData?.result?.collection?.map(({ card }) => card.id));
Por que Set y no Array?

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/pages/[...slug]/index.tsx
> +            <UserProfileImage userImage={userData?.image as string} ownedCardCount={ownedCardCount} />
Yo juntaria UserProfileImage y UserCardRarities en un componente compuesto, algo como: UserSection o algo asi.

2024-10-17 16:55 UTC, serudda commented on apps/nextjs/src/styles/components/profile.css
> +.profile-container {
Why my friend?

2024-10-17 17:23 UTC, Zyruks commented on apps/bot/package.json
> +    "dev2": "pnpm with-env node --import tsx src/index.ts",
Ahhh era para no abrir el bot porque usted estaba jugando. Ups haha

2024-10-17 17:25 UTC, Zyruks commented on apps/nextjs/components.json
> +  "$schema": "https://ui.shadcn.com/schema.json",
Eso es el archvio de setup de Shadcn

2024-10-17 17:25 UTC, Zyruks commented on apps/nextjs/package.json
> +    "lucide-react": "^0.453.0",
Lo mismo Shadcn

2024-10-17 17:28 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/RaritySection.tsx
> +  ownedCardIds: Set<string>;
Set es una colección de elementos únicos sin duplicados.

Aparte Set es más eficiente en el search por lo mismo de 0 duplicados.

Para este caso que tenemos cartas que son únicas, no se duplican y vamos a necesitar hacer search y reordenar a futuro lo veo más útil, ya que a futuro tendremos más y más y más cartas.

2024-10-17 17:30 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/UserProfileImage.tsx
> +      '[ profile-image ]',
My bad no explicarlo.

el [ ] y dentro la clase es una convencion que uso de [CUBECSS](https://cube.fyi/grouping.html)

En resumen, cuando tengo clases que no son utility de tailwind que vienen desde algun archivo .css las pongo dentro de brackets para identificarlas.

2024-10-17 17:31 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/UserProfileImage.tsx
> +      '[ profile-back ]',
Mismo de arriba

2024-10-17 17:31 UTC, Zyruks commented on apps/nextjs/src/lib/utils.ts
> +import { clsx, type ClassValue } from "clsx"
Este creo que es el cn de shadcn ya lo miro igual

2024-10-17 17:32 UTC, Zyruks commented on apps/nextjs/src/styles/components/profile.css
> +.profile-container {
Adivine...

Efectos de animacion

2024-10-17 17:33 UTC, Zyruks commented on apps/bot/package.json
> +    "dev2": "pnpm with-env node --import tsx src/index.ts",
Done!

2024-10-17 17:34 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/RaritySection.tsx
> +  groupByRarity: (rarity: string) => Card[];
Done!

2024-10-17 17:35 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/UserCardRarities.tsx
> +/* _components/UserCardRarities.tsx */
Removed it!

2024-10-17 17:46 UTC, Zyruks commented on apps/nextjs/package.json
> +    "lucide-react": "^0.453.0",
Cambiar el hover-card a tooltip de shadcn y agregar con cva sizes

y remover lucide-react

2024-10-17 17:53 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/RaritySection.tsx
> +  ownedCardIds: Set<string>;
Done!

2024-10-17 18:01 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/UserProfileImage.tsx
> +      '[ profile-image ]',
Agregar profile-container  como transition class abstraerlo

Eliminar corchetes siempre dejar classes que sean de archivos .css de primera

2024-10-18 01:40 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/UserProfileImage.tsx
> +      '[ profile-image ]',
Done!

2024-10-18 01:40 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/components/UserProfileImage.tsx
> +      '[ profile-back ]',
Done!

2024-10-18 01:41 UTC, Zyruks commented on apps/nextjs/src/components/UserCollection/utils/cardUtils.ts
> + * Creates a map of card IDs to the quantity of cards owned
Se modifico!

2024-10-18 01:42 UTC, Zyruks commented on apps/nextjs/src/pages/[...slug]/index.tsx
> +  const ownedCardIds = new Set(collectionData?.result?.collection?.map(({ card }) => card.id));
Done!

2024-10-18 01:53 UTC, Zyruks commented on apps/nextjs/src/styles/components/profile.css
> +.profile-container {
Done!

2024-10-18 02:37 UTC, serudda approved these changes

2024-10-18 02:37 UTC, serudda commented on apps/nextjs/src/common/utils/cn.ts
> +import { clsx, type ClassValue } from "clsx"
Ponle el TODO

2024-10-18 02:37 UTC, serudda commented on apps/nextjs/src/components/pages/user/collection/rarity-section.tsx
> +
Agregar TODO por que la fortma de organizar por Rareza, puede ser 1 de mil...

2024-10-18 02:37 UTC, serudda commented on apps/nextjs/src/components/pages/user/collection/user-sidebar.tsx
> +interface UserSidebarProps {
Agregar TODO por que esto requiere refactor pronto

2024-10-18 02:37 UTC, serudda commented on apps/nextjs/src/components/pages/user/collection/user-sidebar.tsx
> +interface UserSidebarProps {
Esto deberia llamarse Sidebar

2024-10-18 02:38 UTC, serudda approved these changes

2024-10-18 02:38 UTC, serudda commented on apps/nextjs/src/components/pages/user/collection/utils/groupSingleCardById.ts
> +
Renombrar util con el dash

2024-10-18 02:43 UTC, Zyruks commented on apps/nextjs/src/components/pages/user/collection/utils/groupSingleCardById.ts
> +
Done!

2024-10-18 02:43 UTC, Zyruks commented on apps/nextjs/src/components/pages/user/collection/user-sidebar.tsx
> +interface UserSidebarProps {
Done!

2024-10-18 02:44 UTC, Zyruks commented on apps/nextjs/src/components/pages/user/collection/rarity-section.tsx
> +
Done!

2024-10-18 02:47 UTC, Zyruks commented on apps/nextjs/src/common/utils/cn.ts
> +import { clsx, type ClassValue } from "clsx"
Done!

2024-10-18 02:48 UTC, merged